import {
  randomCreatedDate,
  randomUpdatedDate,
} from "@mui/x-data-grid-generator";

export const MockData = [
  {
    id: 1,
    ticketNumber: "scg-23847",
    subject: "support sap crystal report",
    company: "scg chemical",
    contact: "suthichai.s",
    dateTime: randomCreatedDate(),
    module: "add-on locallize",
    status: 0,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 2,
    ticketNumber: "bcp-23848",
    subject: "error in financial report",
    company: "bcp trading",
    contact: "nattapong.t",
    dateTime: randomCreatedDate(),
    module: "financial module",
    status: 1,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 3,
    ticketNumber: "trl-23849",
    subject: "issue with inventory reconciliation",
    company: "thaire logistics",
    contact: "anong.n",
    dateTime: randomCreatedDate(),
    module: "inventory management",
    status: 2,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 4,
    ticketNumber: "scg-23850",
    subject: "unable to create sales order",
    company: "scg chemical",
    contact: "prasert.c",
    dateTime: randomCreatedDate(),
    module: "sales module",
    status: 0,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 5,
    ticketNumber: "bcp-23851",
    subject: "slow performance in reports",
    company: "bcp trading",
    contact: "somchai.p",
    dateTime: randomCreatedDate(),
    module: "reporting module",
    status: 1,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 6,
    ticketNumber: "trl-23852",
    subject: "issue with bank reconciliation",
    company: "thaire logistics",
    contact: "kanya.k",
    dateTime: randomCreatedDate(),
    module: "financial module",
    status: 2,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 7,
    ticketNumber: "scg-23853",
    subject: "add-on feature request",
    company: "scg chemical",
    contact: "thanakorn.t",
    dateTime: randomCreatedDate(),
    module: "add-on locallize",
    status: 0,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 8,
    ticketNumber: "bcp-23854",
    subject: "incorrect tax calculation",
    company: "bcp trading",
    contact: "wanlop.p",
    dateTime: randomCreatedDate(),
    module: "financial module",
    status: 1,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 9,
    ticketNumber: "trl-23855",
    subject: "report customization needed",
    company: "thaire logistics",
    contact: "narin.k",
    dateTime: randomCreatedDate(),
    module: "reporting module",
    status: 2,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 10,
    ticketNumber: "scg-23856",
    subject: "error during data import",
    company: "scg chemical",
    contact: "somchai.s",
    dateTime: randomCreatedDate(),
    module: "data management",
    status: 0,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 11,
    ticketNumber: "bcp-23857",
    subject: "system crash when printing",
    company: "bcp trading",
    contact: "jirasak.p",
    dateTime: randomCreatedDate(),
    module: "printing module",
    status: 1,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 12,
    ticketNumber: "trl-23858",
    subject: "license activation issue",
    company: "thaire logistics",
    contact: "somchai.p",
    dateTime: randomCreatedDate(),
    module: "licensing",
    status: 2,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 13,
    ticketNumber: "scg-23859",
    subject: "support sap crystal report",
    company: "scg chemical",
    contact: "thongchai.k",
    dateTime: randomCreatedDate(),
    module: "add-on locallize",
    status: 0,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 14,
    ticketNumber: "bcp-23860",
    subject: "error in financial report",
    company: "bcp trading",
    contact: "arunee.r",
    dateTime: randomCreatedDate(),
    module: "financial module",
    status: 1,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 15,
    ticketNumber: "trl-23861",
    subject: "issue with inventory reconciliation",
    company: "thaire logistics",
    contact: "wattana.y",
    dateTime: randomCreatedDate(),
    module: "inventory management",
    status: 2,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 16,
    ticketNumber: "scg-23862",
    subject: "unable to create sales order",
    company: "scg chemical",
    contact: "yuthana.p",
    dateTime: randomCreatedDate(),
    module: "sales module",
    status: 0,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 17,
    ticketNumber: "bcp-23863",
    subject: "slow performance in reports",
    company: "bcp trading",
    contact: "arun.t",
    dateTime: randomCreatedDate(),
    module: "reporting module",
    status: 1,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 18,
    ticketNumber: "trl-23864",
    subject: "issue with bank reconciliation",
    company: "thaire logistics",
    contact: "wattana.y",
    dateTime: randomCreatedDate(),
    module: "financial module",
    status: 2,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 19,
    ticketNumber: "scg-23865",
    subject: "add-on feature request",
    company: "scg chemical",
    contact: "somchai.k",
    dateTime: randomCreatedDate(),
    module: "add-on locallize",
    status: 0,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 20,
    ticketNumber: "bcp-23866",
    subject: "incorrect tax calculation",
    company: "bcp trading",
    contact: "sarawut.n",
    dateTime: randomCreatedDate(),
    module: "financial module",
    status: 1,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 21,
    ticketNumber: "trl-23867",
    subject: "report customization needed",
    company: "thaire logistics",
    contact: "narin.s",
    dateTime: randomCreatedDate(),
    module: "reporting module",
    status: 2,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 22,
    ticketNumber: "scg-23868",
    subject: "error during data import",
    company: "scg chemical",
    contact: "somchai.s",
    dateTime: randomCreatedDate(),
    module: "data management",
    status: 0,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 23,
    ticketNumber: "bcp-23869",
    subject: "system crash when printing",
    company: "bcp trading",
    contact: "jirasak.p",
    dateTime: randomCreatedDate(),
    module: "printing module",
    status: 1,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 24,
    ticketNumber: "trl-23870",
    subject: "license activation issue",
    company: "thaire logistics",
    contact: "somchai.p",
    dateTime: randomCreatedDate(),
    module: "licensing",
    status: 2,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 25,
    ticketNumber: "scg-23871",
    subject: "support sap crystal report",
    company: "scg chemical",
    contact: "thongchai.k",
    dateTime: randomCreatedDate(),
    module: "add-on locallize",
    status: 0,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 26,
    ticketNumber: "bcp-23872",
    subject: "error in financial report",
    company: "bcp trading",
    contact: "arunee.r",
    dateTime: randomCreatedDate(),
    module: "financial module",
    status: 1,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 27,
    ticketNumber: "trl-23873",
    subject: "issue with inventory reconciliation",
    company: "thaire logistics",
    contact: "wattana.y",
    dateTime: randomCreatedDate(),
    module: "inventory management",
    status: 2,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 28,
    ticketNumber: "scg-23874",
    subject: "unable to create sales order",
    company: "scg chemical",
    contact: "yuthana.p",
    dateTime: randomCreatedDate(),
    module: "sales module",
    status: 0,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 29,
    ticketNumber: "bcp-23875",
    subject: "slow performance in reports",
    company: "bcp trading",
    contact: "arun.t",
    dateTime: randomCreatedDate(),
    module: "reporting module",
    status: 1,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 30,
    ticketNumber: "trl-23876",
    subject: "issue with bank reconciliation",
    company: "thaire logistics",
    contact: "wattana.y",
    dateTime: randomCreatedDate(),
    module: "financial module",
    status: 2,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 31,
    ticketNumber: "scg-23877",
    subject: "add-on feature request",
    company: "scg chemical",
    contact: "somchai.k",
    dateTime: randomCreatedDate(),
    module: "add-on locallize",
    status: 0,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 32,
    ticketNumber: "bcp-23878",
    subject: "incorrect tax calculation",
    company: "bcp trading",
    contact: "sarawut.n",
    dateTime: randomCreatedDate(),
    module: "financial module",
    status: 1,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 33,
    ticketNumber: "trl-23879",
    subject: "report customization needed",
    company: "thaire logistics",
    contact: "narin.s",
    dateTime: randomCreatedDate(),
    module: "reporting module",
    status: 2,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 34,
    ticketNumber: "scg-23880",
    subject: "error during data import",
    company: "scg chemical",
    contact: "somchai.s",
    dateTime: randomCreatedDate(),
    module: "data management",
    status: 0,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 35,
    ticketNumber: "bcp-23881",
    subject: "system crash when printing",
    company: "bcp trading",
    contact: "jirasak.p",
    dateTime: randomCreatedDate(),
    module: "printing module",
    status: 1,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 36,
    ticketNumber: "trl-23882",
    subject: "license activation issue",
    company: "thaire logistics",
    contact: "somchai.p",
    dateTime: randomCreatedDate(),
    module: "licensing",
    status: 2,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 37,
    ticketNumber: "scg-23883",
    subject: "support sap crystal report",
    company: "scg chemical",
    contact: "thongchai.k",
    dateTime: randomCreatedDate(),
    module: "add-on locallize",
    status: 0,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 38,
    ticketNumber: "bcp-23884",
    subject: "error in financial report",
    company: "bcp trading",
    contact: "arunee.r",
    dateTime: randomCreatedDate(),
    module: "financial module",
    status: 1,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 39,
    ticketNumber: "trl-23885",
    subject: "issue with inventory reconciliation",
    company: "thaire logistics",
    contact: "wattana.y",
    dateTime: randomCreatedDate(),
    module: "inventory management",
    status: 2,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 40,
    ticketNumber: "scg-23886",
    subject: "unable to create sales order",
    company: "scg chemical",
    contact: "yuthana.p",
    dateTime: randomCreatedDate(),
    module: "sales module",
    status: 0,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 41,
    ticketNumber: "bcp-23887",
    subject: "slow performance in reports",
    company: "bcp trading",
    contact: "arun.t",
    dateTime: randomCreatedDate(),
    module: "reporting module",
    status: 1,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 42,
    ticketNumber: "trl-23888",
    subject: "issue with bank reconciliation",
    company: "thaire logistics",
    contact: "wattana.y",
    dateTime: randomCreatedDate(),
    module: "financial module",
    status: 2,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 43,
    ticketNumber: "scg-23889",
    subject: "add-on feature request",
    company: "scg chemical",
    contact: "somchai.k",
    dateTime: randomCreatedDate(),
    module: "add-on locallize",
    status: 0,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 44,
    ticketNumber: "bcp-23890",
    subject: "incorrect tax calculation",
    company: "bcp trading",
    contact: "sarawut.n",
    dateTime: randomCreatedDate(),
    module: "financial module",
    status: 1,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 45,
    ticketNumber: "trl-23891",
    subject: "report customization needed",
    company: "thaire logistics",
    contact: "narin.s",
    dateTime: randomCreatedDate(),
    module: "reporting module",
    status: 2,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 46,
    ticketNumber: "scg-23892",
    subject: "error during data import",
    company: "scg chemical",
    contact: "somchai.s",
    dateTime: randomCreatedDate(),
    module: "data management",
    status: 0,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 47,
    ticketNumber: "bcp-23893",
    subject: "system crash when printing",
    company: "bcp trading",
    contact: "jirasak.p",
    dateTime: randomCreatedDate(),
    module: "printing module",
    status: 1,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 48,
    ticketNumber: "trl-23894",
    subject: "license activation issue",
    company: "thaire logistics",
    contact: "somchai.p",
    dateTime: randomCreatedDate(),
    module: "licensing",
    status: 2,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 49,
    ticketNumber: "scg-23895",
    subject: "support sap crystal report",
    company: "scg chemical",
    contact: "thongchai.k",
    dateTime: randomCreatedDate(),
    module: "add-on locallize",
    status: 0,
    convertDateTime: randomCreatedDate(),
  },
  {
    id: 50,
    ticketNumber: "bcp-23896",
    subject: "error in financial report",
    company: "bcp trading",
    contact: "arunee.r",
    dateTime: randomCreatedDate(),
    module: "financial module",
    status: 1,
    convertDateTime: randomCreatedDate(),
  },
];
